import "./src/utils/polyfills";
import React, { useState, useEffect } from "react";
import { StatusBar } from "expo-status-bar";
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Text, View, StyleSheet, Platform, useWindowDimensions, Modal, TouchableOpacity, ScrollView } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { COLORS } from "./src/config/constants";
import ConnectScreen from "./src/screens/ConnectScreen";
import PortfolioScreen from "./src/screens/PortfolioScreen";
import AIScreen from "./src/screens/AIScreen";
import RecommendationsScreen from "./src/screens/RecommendationsScreen";
import SettingsScreen from "./src/screens/SettingsScreen";

const DISCLAIMER_KEY = "@seeker_copilot_disclaimer_v1";

const Tab = createBottomTabNavigator();

// Solana Seeker phone: 6.36" AMOLED, 1080x2400 → logical 393x873
const SEEKER_WIDTH = 393;
const SEEKER_HEIGHT = 873;

function TabIcon({ icon, label, focused }: { icon: string; label: string; focused: boolean }) {
  const color = focused ? COLORS.secondary : COLORS.textSecondary;
  return (
    <View style={{ alignItems: "center", gap: 2 }}>
      <Text style={{ fontSize: 18, color }}>{icon}</Text>
      <Text style={{ fontSize: 9, fontWeight: "600", color, letterSpacing: 0.3 }}>{label}</Text>
    </View>
  );
}

function MainApp() {
  return (
    <NavigationContainer>
      <Tab.Navigator
        screenOptions={{
          headerStyle: { backgroundColor: COLORS.background, elevation: 0, shadowOpacity: 0, borderBottomWidth: 1, borderBottomColor: COLORS.border },
          headerTintColor: COLORS.text,
          headerTitleStyle: { fontWeight: "700" },
          tabBarStyle: { backgroundColor: COLORS.surface, borderTopColor: COLORS.border, borderTopWidth: 1, height: 60, paddingBottom: 8, paddingTop: 4 },
          tabBarActiveTintColor: COLORS.secondary,
          tabBarInactiveTintColor: COLORS.textSecondary,
        }}
      >
        <Tab.Screen
          name="Portfolio"
          component={PortfolioScreen}
          options={{ tabBarIcon: ({ focused }) => <TabIcon icon="◎" label="Portfolio" focused={focused} />, tabBarLabel: () => null }}
        />
        <Tab.Screen
          name="AI Copilot"
          component={AIScreen}
          options={{ tabBarIcon: ({ focused }) => <TabIcon icon="✦" label="Copilot" focused={focused} />, tabBarLabel: () => null }}
        />
        <Tab.Screen
          name="Intel"
          component={RecommendationsScreen}
          options={{ tabBarIcon: ({ focused }) => <TabIcon icon="⚡" label="Intel" focused={focused} />, tabBarLabel: () => null }}
        />
        <Tab.Screen
          name="Settings"
          component={SettingsScreen}
          options={{ tabBarIcon: ({ focused }) => <TabIcon icon="⚙" label="Settings" focused={focused} />, tabBarLabel: () => null }}
        />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

/** Desktop phone frame that simulates Solana Seeker device */
function PhoneFrame({ children }: { children: React.ReactNode }) {
  const { width, height } = useWindowDimensions();
  // Only show frame on wide screens (desktop browser)
  if (width < 500) return <>{children}</>;

  return (
    <View style={frameStyles.backdrop}>
      {/* Device label */}
      <Text style={frameStyles.deviceLabel}>Solana Seeker</Text>
      {/* Phone bezel */}
      <View style={frameStyles.bezel}>
        {/* Notch / camera cutout */}
        <View style={frameStyles.notchRow}>
          <View style={frameStyles.notch}>
            <View style={frameStyles.camera} />
          </View>
        </View>
        {/* App content */}
        <View style={frameStyles.screen}>{children}</View>
      </View>
      <Text style={frameStyles.hint}>Demo Mode — Simulated Seeker Phone</Text>
    </View>
  );
}

function DisclaimerModal({ onAccept }: { onAccept: () => void }) {
  return (
    <Modal transparent animationType="fade" visible statusBarTranslucent>
      <View style={disclaimerStyles.backdrop}>
        <View style={disclaimerStyles.card}>
          <View style={disclaimerStyles.iconRow}>
            <Text style={disclaimerStyles.icon}>⚠️</Text>
          </View>
          <Text style={disclaimerStyles.title}>Important Disclaimer</Text>
          <ScrollView style={disclaimerStyles.scroll} showsVerticalScrollIndicator={false}>
            <Text style={disclaimerStyles.body}>
              Seeker AI Copilot provides <Text style={disclaimerStyles.bold}>AI-generated portfolio analysis for informational purposes only.</Text>
              {"\n\n"}
              Nothing in this app constitutes financial advice, investment advice, trading advice, or any other type of advice. The AI signals, risk scores, and trade recommendations are generated by automated systems and{" "}
              <Text style={disclaimerStyles.bold}>should not be relied upon to make financial decisions.</Text>
              {"\n\n"}
              Cryptocurrency investments are highly volatile and involve substantial risk of loss. Past performance is not indicative of future results. Always do your own research (DYOR) and consult a qualified financial advisor before making investment decisions.
              {"\n\n"}
              By continuing, you acknowledge that you have read and understood this disclaimer.
            </Text>
          </ScrollView>
          <TouchableOpacity style={disclaimerStyles.acceptBtn} onPress={onAccept} activeOpacity={0.85}>
            <Text style={disclaimerStyles.acceptText}>I Understand — Continue</Text>
          </TouchableOpacity>
          <Text style={disclaimerStyles.footer}>
            View our{" "}
            <Text style={disclaimerStyles.link}>Privacy Policy</Text>
            {" "}in Settings → About
          </Text>
        </View>
      </View>
    </Modal>
  );
}

export default function App() {
  const [connected, setConnected] = useState(Platform.OS === "web");
  const [disclaimerAccepted, setDisclaimerAccepted] = useState<boolean | null>(null);

  useEffect(() => {
    AsyncStorage.getItem(DISCLAIMER_KEY).then((val) => {
      setDisclaimerAccepted(val === "true");
    }).catch(() => setDisclaimerAccepted(false));
  }, []);

  const handleAcceptDisclaimer = async () => {
    try { await AsyncStorage.setItem(DISCLAIMER_KEY, "true"); } catch { /* ignore */ }
    setDisclaimerAccepted(true);
  };

  // Don't render until disclaimer state is loaded
  if (disclaimerAccepted === null) return null;

  const appContent = connected ? <MainApp /> : <ConnectScreen onConnected={() => setConnected(true)} />;

  return (
    <>
      <StatusBar style="light" />
      {!disclaimerAccepted && <DisclaimerModal onAccept={handleAcceptDisclaimer} />}
      {Platform.OS === "web" ? <PhoneFrame>{appContent}</PhoneFrame> : appContent}
    </>
  );
}

const styles = StyleSheet.create({
  tabLabel: { fontSize: 16, fontWeight: "800" },
});

const disclaimerStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  iconRow: {
    alignItems: "center",
    marginBottom: 12,
  },
  icon: {
    fontSize: 32,
  },
  title: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  scroll: {
    maxHeight: 240,
    marginBottom: 20,
  },
  body: {
    color: COLORS.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  bold: {
    color: COLORS.text,
    fontWeight: "700",
  },
  acceptBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  acceptText: {
    color: COLORS.text,
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  footer: {
    color: COLORS.textMuted,
    fontSize: 11,
    textAlign: "center",
    lineHeight: 16,
  },
  link: {
    color: COLORS.primary,
    textDecorationLine: "underline",
  },
});

const frameStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "#0a0a0f",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 16,
  },
  deviceLabel: {
    color: "#666",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  bezel: {
    width: SEEKER_WIDTH + 16,
    height: SEEKER_HEIGHT + 16,
    backgroundColor: "#1a1a2e",
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#333",
    padding: 8,
    // Shadow for depth
    shadowColor: "#9945FF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 30,
    overflow: "hidden",
  },
  notchRow: {
    position: "absolute",
    top: 8,
    left: 0,
    right: 0,
    zIndex: 10,
    alignItems: "center",
  },
  notch: {
    width: 100,
    height: 28,
    backgroundColor: "#000",
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  camera: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#1a1a2e",
    borderWidth: 1,
    borderColor: "#333",
  },
  screen: {
    flex: 1,
    borderRadius: 32,
    overflow: "hidden",
    backgroundColor: COLORS.background,
  },
  hint: {
    color: "#555",
    fontSize: 11,
    marginTop: 12,
    letterSpacing: 0.5,
  },
});
